<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FonctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionRepository extends EntityRepository
{
    
}
